[build]
  command = "VITE_API_URL=https://trace-examsecurityoperations-production.up.railway.app npm run build"
  base = "frontend"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
